name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "xaea12-backend"
          heroku_email: "adli.daffa5@gmail.com"
          healthcheck: "https://xaea12-backend.herokuapp.com/health"
